[General]
private-ip-answer = true
hijack-dns = 
fallback-dns-server = system
bypass-system = true
skip-proxy = 192.168.0.0/16,10.0.0.0/8,172.16.0.0/12,localhost,*.local,captive.apple.com
bypass-tun = 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.0.0.0/24, 192.0.2.0/24, 192.88.99.0/24, 192.168.0.0/16, 198.18.0.0/15, 198.51.100.0/24, 203.0.113.0/24, 224.0.0.0/4, 255.255.255.255/32
dns-server = https://dns.quad9.net/dns-query
update-url = https://raw.githubusercontent.com/Master-Yoba/shadowrocket-config/main/sr_blocked_tier_1.conf

[Rule]
# private
IP-CIDR,192.168.0.0/16,DIRECT
IP-CIDR,10.0.0.0/8,DIRECT
IP-CIDR,172.16.0.0/12,DIRECT
IP-CIDR,127.0.0.0/8,DIRECT
# ads
RULE-SET,https://raw.githubusercontent.com/Master-Yoba/shadowrocket-rules/refs/heads/release/rules-geosite/geosite-category-ru%40ads.list,REJECT
DOMAIN-SUFFIX,1.adfox.ru,REJECT
DOMAIN-SUFFIX,4smi.ru,REJECT
DOMAIN-SUFFIX,adfox.me,REJECT
DOMAIN-SUFFIX,adfox.yandex.ru,REJECT
DOMAIN-SUFFIX,ads.adfox.ru,REJECT
DOMAIN-SUFFIX,an.yandex.ru,REJECT
DOMAIN-SUFFIX,banners.adfox.net,REJECT
DOMAIN-SUFFIX,help.adfox.ru,REJECT
DOMAIN-SUFFIX,iva.adfox.ru,REJECT
DOMAIN-SUFFIX,mc.yandex.ru,REJECT
DOMAIN-SUFFIX,myt.adfox.ru,REJECT
DOMAIN-SUFFIX,smi2.ru,REJECT
# ru
RULE-SET,https://raw.githubusercontent.com/Master-Yoba/shadowrocket-rules/release/rules-geosite/geosite-category-ru.list,DIRECT
DOMAIN-SUFFIX,by,DIRECT
DOMAIN-SUFFIX,googlevideo.com,PROXY
GEOIP,RU,DIRECT
# checkers
RULE-SET,https://raw.githubusercontent.com/Master-Yoba/shadowrocket-rules/release/rules-geosite/geosite-category-ip-geo-detect.list,DIRECT
# blocked
RULE-SET,https://raw.githubusercontent.com/Master-Yoba/shadowrocket-rules/refs/heads/release/rules-geosite/geosite-ru-blocked.list,PROXY
FINAL,DIRECT

[Host]
ntc.party = 130.255.77.28
localhost = 127.0.0.1

[URL Rewrite]
^http://(www.)?g.ru https://www.google.com HEADER
^http://(www.)?google.ru https://www.google.com HEADER
^http://(www.)?yandex.ru https://www.ya.ru 302
